//
// Created by Administrator on 2016/3/25.
//

#ifndef ANDROIDDEMO_AUTOUTF8TOJAVASTRING_H
#define ANDROIDDEMO_AUTOUTF8TOJAVASTRING_H


class AutoUTF8ToJavaString {

};


#endif //ANDROIDDEMO_AUTOUTF8TOJAVASTRING_H
