/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hubery_androiddemo_ui_jni_JniCore */

#ifndef _Included_com_hubery_androiddemo_ui_jni_JniCore
#define _Included_com_hubery_androiddemo_ui_jni_JniCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hubery_androiddemo_ui_jni_JniCore
 * Method:    add
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hubery_androiddemo_jni_JniCore_add
        (JNIEnv *, jclass);

/*
 * Class:     com_hubery_androiddemo_ui_jni_JniCore
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hubery_androiddemo_jni_JniCore_hello
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
